name: ledflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.3.2
  flutter_colorpicker: ^1.1.0
  flutter_inner_shadow: ^0.0.1
  flutter_local_notifications: ^17.2.1
  flutter_neumorphic: ^3.2.0
  flutter_neumorphic_plus: ^3.3.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  interactive_slider: ^0.2.2
  permission_handler: ^11.3.1
  simple_shadow: ^0.3.1
  starsview: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/foco.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/wear-7484f-firebase-adminsdk-y8951-40d336b7bb.json
